version: "3.1"

services:
  consignment-client:
    build: ./consignment-client
    image: consignment-client
    environment:
      MICRO_REGISTRY: "mdns"

  consignment-service:
    build: ./consignment-service
    image: consignment-service
    ports:
      - 50051:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"

  vessel-service:
    build: ./vessel-service
    image: vessel-service
    ports:
      - 50052:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "mongodb://datastore:27017"
    depends_on:
      - datastore

  datastore:
    image: mongo
    ports:
      - 27017:27017